# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Joseph Slinker
email: your-email@domain.com
description: > # I design and build software to make people's lives
                just a little bit better. I write about iOS development,
                Swift, Cocoa, and sometimes art and culture.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://josephslinker.com" # the base hostname & protocol for your site
twitter_username: theslinker
github_username:  jslinker

# Build settings
markdown: kramdown
